###############################################################
#  Generated by:      Cadence Innovus 21.35-s114_1
#  OS:                Linux x86_64(Host ID cn89.it.auth.gr)
#  Generated on:      Sun Feb 23 22:10:17 2025
#  Design:            picorv32
#  Command:           create_ccopt_clock_tree_spec -file /home/d/deirmentz/VLSI_ASIC/Exercises/Exercise6/Clock_Step14_6.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clk (period 5.000ns) in timing_config Constraint_Mode_Exer1([genus_invs_des/genus.default_emulate_constraint_mode.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner Delay_Corner_Exer1 -early -clock_tree clk 0.050
set_ccopt_property target_max_trans_sdc -delay_corner Delay_Corner_Exer1 -late -clock_tree clk 0.050
set_ccopt_property source_driver -clock_tree clk {BUFX4/A BUFX4/Y}
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 5

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:Constraint_Mode_Exer1 (sdc genus_invs_des/genus.default_emulate_constraint_mode.sdc)
create_ccopt_skew_group -name clk/Constraint_Mode_Exer1 -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/Constraint_Mode_Exer1 true
set_ccopt_property extracted_from_clock_name -skew_group clk/Constraint_Mode_Exer1 clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/Constraint_Mode_Exer1 Constraint_Mode_Exer1
set_ccopt_property extracted_from_delay_corners -skew_group clk/Constraint_Mode_Exer1 Delay_Corner_Exer1


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

