###############################################################
#  Generated by:      Cadence Innovus 21.35-s114_1
#  OS:                Linux x86_64(Host ID cn98.it.auth.gr)
#  Generated on:      Sun Feb 23 06:25:26 2025
#  Design:            picorv32
#  Command:           create_ccopt_clock_tree_spec -file /home/d/deirmentz/VLSI_ASIC/Exercises/Exercise4/Clock_Step14_4.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Pin offsets inferred from set_clock_latency assertions:
set_ccopt_property insertion_delay -pin latched_branch_reg/CK 0.045
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[0]/CK} 0.667
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[10]/CK} 0.641
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[11]/CK} 0.640
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[12]/CK} 0.667
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[13]/CK} 0.672
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[14]/CK} 0.648
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[15]/CK} 0.669
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[16]/CK} 0.610
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[17]/CK} 0.710
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[18]/CK} 0.667
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[19]/CK} 0.705
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[1]/CK} 0.602
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[20]/CK} 0.641
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[21]/CK} 0.667
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[22]/CK} 0.670
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[23]/CK} 0.643
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[24]/CK} 0.705
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[25]/CK} 0.613
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[26]/CK} 0.613
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[27]/CK} 0.640
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[28]/CK} 0.648
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[29]/CK} 0.666
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[2]/CK} 0.662
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[30]/CK} 0.681
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[31]/CK} 0.609
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[32]/CK} 0.600
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[3]/CK} 0.640
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[4]/CK} 0.587
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[5]/CK} 0.599
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[6]/CK} 0.599
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[7]/CK} 0.643
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[8]/CK} 0.604
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs1_reg[9]/CK} 0.644
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[0]/CK} 0.585
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[10]/CK} 0.681
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[11]/CK} 0.710
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[12]/CK} 0.598
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[13]/CK} 0.708
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[14]/CK} 0.676
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[15]/CK} 0.732
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[16]/CK} 0.712
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[17]/CK} 0.712
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[18]/CK} 0.646
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[19]/CK} 0.712
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[1]/CK} 0.712
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[20]/CK} 0.606
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[21]/CK} 0.708
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[22]/CK} 0.616
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[23]/CK} 0.673
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[24]/CK} 0.671
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[25]/CK} 0.727
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[26]/CK} 0.689
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[27]/CK} 0.690
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[28]/CK} 0.609
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[29]/CK} 0.668
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[2]/CK} 0.721
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[30]/CK} 0.645
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[31]/CK} 0.649
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[32]/CK} 0.612
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[3]/CK} 0.726
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[4]/CK} 0.701
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[5]/CK} 0.711
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[6]/CK} 0.640
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[7]/CK} 0.715
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[8]/CK} 0.703
set_ccopt_property insertion_delay -pin {genblk1.pcpi_mul_rs2_reg[9]/CK} 0.711

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clk (period 2.500ns) in timing_config Constraint_Mode_Exer1([genus_invs_des/genus.default_emulate_constraint_mode.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner Delay_Corner_Exer1 -early -clock_tree clk 0.025
set_ccopt_property target_max_trans_sdc -delay_corner Delay_Corner_Exer1 -late -clock_tree clk 0.025
set_ccopt_property source_driver -clock_tree clk {BUFX4/A BUFX4/Y}
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 2.5

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:Constraint_Mode_Exer1 (sdc genus_invs_des/genus.default_emulate_constraint_mode.sdc)
create_ccopt_skew_group -name clk/Constraint_Mode_Exer1 -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/Constraint_Mode_Exer1 true
set_ccopt_property extracted_from_clock_name -skew_group clk/Constraint_Mode_Exer1 clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/Constraint_Mode_Exer1 Constraint_Mode_Exer1
set_ccopt_property extracted_from_delay_corners -skew_group clk/Constraint_Mode_Exer1 Delay_Corner_Exer1


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

